name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Package check
        run: cargo check

      - name: Build
        run: cargo build

      - name: Lint
        run: cargo clippy

      - name: Test
        run: cargo test
